require: rubocop-rspec

AllCops:
  Exclude:
    - Gemfile
    - texttest_fixture.rb
    - gilded_rose_tests.rb

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

# TODO:
Metrics:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/SoleNestedConditional:
  Enabled: false
