require: rubocop-rspec

AllCops:
  NewCops: disable
  Exclude:
    - Gemfile
    - texttest_fixture.rb
    - gilded_rose_tests.rb

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

# TODO:
RSpec/MultipleExpectations:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false
